// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using resurec.DbContexts;

#nullable disable

namespace resurec.Migrations
{
    [DbContext(typeof(ResurecDbContext))]
    [Migration("20241203172504_Dec03")]
    partial class Dec03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("resurec.DTOs.HardwareReportDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("CpuTemperature")
                        .HasColumnType("REAL");

                    b.Property<float>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<float>("GpuTemperature")
                        .HasColumnType("REAL");

                    b.Property<float>("GpuUsage")
                        .HasColumnType("REAL");

                    b.Property<float>("RamUsage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("HardwareReportDTO");
                });

            modelBuilder.Entity("resurec.DTOs.RecordingDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HardwareReportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HardwareReportId");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("resurec.DTOs.RecordingDTO", b =>
                {
                    b.HasOne("resurec.DTOs.HardwareReportDTO", "HardwareReport")
                        .WithMany()
                        .HasForeignKey("HardwareReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HardwareReport");
                });
#pragma warning restore 612, 618
        }
    }
}
